n = (input('Digite algo '))
print('O tipo primitivo desse valor é: ', type(n))
print('Só tem espaços? ', n.isspace() )
print('É um número? ', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico? ', n.isalnum())
print('É decimal? ', n.isdecimal()) 
print('É maiúsucula? ', n.isupper())
print('É minúsculo? ', n.islower())
print('Está capitalizado?', n.istitle())